version: "2.4"

x-brightsky:
  &brightsky
  build: .
  depends_on:
    - postgres
    - redis
  env_file:
    brightsky.env

services:
  postgres:
    image: postgres:12-alpine
    shm_size: 512mb
    environment:
      POSTGRES_PASSWORD: pgpass
    volumes:
      - .data:/var/lib/postgresql/data
    restart: always
    networks:
      - backend
  redis:
    image: redis:5-alpine
    restart: always
    networks:
      - backend
  worker:
    <<: *brightsky
    command: --migrate work
    restart: always
    networks:
      - backend
  web:
    <<: *brightsky
    container_name: brightsky_frontend
    command: serve --bind 0.0.0.0:5000
    restart: always
    networks:
      - backend
      - api
  brightsky:
    <<: *brightsky
    scale: 0
    networks:
      - backend

  
networks:
  backend:
    driver: bridge
  api:
    driver: bridge
